# Generated by Django 4.1.5 on 2023-01-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='ID гравця')),
                ('name', models.TextField(verbose_name="Ім'я гравця")),
            ],
            options={
                'verbose_name': 'Профіль гравця',
            },
        ),
    ]
