# Generated by Django 4.1.5 on 2023-02-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_player_options_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hostage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.player', verbose_name='Власник'),
        ),
        migrations.AlterField(
            model_name='player',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID гравця'),
        ),
    ]
