# Generated by Django 4.1.5 on 2023-03-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_player_hostage_alter_player_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hostage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.player', verbose_name='Заручник'),
        ),
    ]
