# Generated by Django 4.1.5 on 2023-03-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_player_hostage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.PositiveIntegerField(blank=True, null=True, verbose_name='HP')),
                ('energy', models.PositiveIntegerField(blank=True, null=True, verbose_name='Energy')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='hryvni',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hryvni'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('decoration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_on_position', to='test_app.decoration', verbose_name='Decoration')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='test_app.type', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_events', to='test_app.type', verbose_name='Type')),
            ],
        ),
        migrations.AddField(
            model_name='decoration',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_decorations', to='test_app.type', verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Basement',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('hostage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_hostage', to='test_app.player', verbose_name='Hostage')),
                ('master', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_master', to='test_app.player', verbose_name='Master')),
                ('position', models.ManyToManyField(related_name='%(class)s_in_basement', to='test_app.position', verbose_name='Position')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='basement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_player', to='test_app.basement', verbose_name='Basement'),
        ),
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.ManyToManyField(to='test_app.item', verbose_name='Inventory'),
        ),
        migrations.AddField(
            model_name='player',
            name='stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_player', to='test_app.stats', verbose_name='Stats'),
        ),
    ]
