# Generated by Django 4.1.5 on 2023-03-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_decoration_stats_type_player_hryvni_position_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('probability', models.FloatField(verbose_name='Probability')),
            ],
        ),
    ]
