# Generated by Django 4.1.5 on 2023-03-07 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_alter_eventresult_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresult',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.item', verbose_name='Item Found'),
        ),
    ]
